name: Update timestamp
on:
  schedule:
    - cron: '0 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update timestamp
        run: sed -i "s/{{DATE}}/$(date +'%Y-%m-%d %H:%M:%S')/g" README.md
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update timestamp"
